@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1MDEwNDYxNn0.fWUkSZkWTdMPfi7_vN9h3fh-mtCEajLies76XNrJQnY
### Create a new user
POST http://localhost:4000/signup
Content-Type: application/json

{
  "Fname": "John Doe",
  " Lname":,
  " phone":,
  "email": "whiteocjd@gmail.com",
  "password":"1234",
  "country":,
  "type":"shopKeeper"
}
###check code
POST http://localhost:4000/verify
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com",
  "checkCode": "0"
}


###log in
POST http://localhost:4000/logIn
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com",
  "password": "1234"
}

### forget password
POST http://localhost:4000/forget-password
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com"
}

### Reset-password
POST http://localhost:4000/reset-password
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com",
  "newPassword":"1244",
  "resetCode":0
}

### Get profile
GET http://localhost:4000/profile
Authorization: Bearer {{token}}
Content-Type: application/json

### Get my product
GET http://localhost:4000/getMyProduct
Authorization: Bearer {{token}}
Content-Type: application/json

### Add battery
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json
# product data same for all product
{
  "productData":{
    "category":"battery",
    "description":"",
     "price":"100",
    "name": "battery",
    "picture":""
    
  },
  "additionalData":{
    "batteryType":"1",
    "batterySize":"55"
  }
}

### Update battery
put http://localhost:4000/updateProduct/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData":{
    "category":"battery"
  },
  "additionalData":{
    "batteryType":"3",
    "batterySize":"77"
  }
}
###add inverter
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData":{
    "category":"inverter",
    "price":"100",
    "name": "inverter3",
    "description":" "

  },
  "additionalData":{
    "inverterRatingP":"1",
      "maxAc": "2",
      "defaultAc": ,
      "solarRatingP": ,
      "maxSolarVolt": ,
      "Mppt": 
  }
}
### Add solar panel
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData":{
    "category":"solar panel",
    "price":"100",
    "name": "solar panel"

  },
  "additionalData":{
     "maximumPower": ,
      "shortCurrent":,
      "openVoltage":
  }
}
### Add Review
POST http://localhost:4000/addReview
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 8,
  "review": "This product is great!",
  "stars": 5
}

###test add product with picture in cmd 
curl -X POST http://localhost:4000/addProduct ^
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc0OTc2MzAzNX0.URiPjUXvmDRIH0q2AoXL30x4M8Z6ffUKvuoXhVSC3BQ" ^
  -F "productData={\"category\":\"inverter\",\"price\":\"10\",\"name\":\"inverter2\"}" ^
  -F "additionalData={\"inverterRatingP\":\"2\"}" ^
  -F "picture=@profile.jpg"

### Get all product
GET http://localhost:4000/getAllProduct
Content-Type: application/json

### Upload profile picture
# in cmd 
# curl -X POST http://localhost:4000/upload-profile-pic ^
#   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc0OTc2MzAzNX0.URiPjUXvmDRIH0q2AoXL30x4M8Z6ffUKvuoXhVSC3BQ" ^
#   -F "profilePic=@profile.jpg"

### Fetch chat messages
GET http://localhost:4000/chat/2
Authorization: Bearer {{token}}

### Add new link
POST http://localhost:4000/addLinks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "linkInfo": {
    "linkName": "GitHub",
    "link": "https://github.com/myusername"
  }
}

### Estimate Solar Energy
#uvicorn solar_api:app --reload بستخدم هي التعليمة لشغل هي 
POST http://127.0.0.1:8000/estimate_energy
Content-Type: application/json

{
  "latitude": 33.5138,
  "longitude": 36.2765,
  "efficiency": 0.20,
  "area": 1.6,
  "system_losses": 0.25,
  "start_date": "2026-12-01",
  "end_date": "2026-12-01"
}
###solarSupplies
POST http://localhost:4000/solarSupplies
Content-Type: application/json

{
  "latitude": 25.276987,
  "longitude": 55.296249,
  "solarPanel": 450,
  "numNight": 2,
  "eDay": 5,
  "eNight": 3,
  "batteryType": "tubular"
}
###Solar Panel Orientation
POST http://localhost:4000/SolarPanelOrientation
Content-Type: application/json

{
  "latitude": 25.276987,
  "longitude": 55.296249
}
