@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1NzI0MzU5NCwiZXhwIjoxNzU3MjU0Mzk0fQ.-0Gp5CxFJUDmtjZ4og3zKe_Ydn5zlZTvWiOqtTkKcZg
### Create a new user
POST http://localhost:4000/signup
Content-Type: application/json

{
  "Fname": "maiss",
  " Lname":"wanous",
  " phone":"0987654321",
  "email": "shop@gmail.com",
  "password":"1234",
  "country":"",
  "type":"shopKeeper",
  "shop_name":"shop",
  "shop_phone":"999999"
}
###check code
POST http://localhost:4000/verify
Content-Type: application/json

{
  "email": "shop@gmail.com",
  "checkCode": "0"
}


###log in
POST http://localhost:4000/logIn
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com",
  "password": "1246"
}

###get refresh token
GET  http://localhost:4000/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

### forget password
POST http://localhost:4000/forget-password
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com"
}

### Reset-password
POST http://localhost:4000/reset-password
Content-Type: application/json

{
  "email": "whiteocjd@gmail.com",
  "newPassword":"1246",
  "resetCode":0
}

### Reset-password for user with login
POST http://localhost:4000/reset-Mypassword
Authorization: Bearer {{token}}
Content-Type: application/json

{
"oldPassword":"1234",
"newPassword":"1235"
}

### Get profile
GET http://localhost:4000/profile
Authorization: Bearer {{token}}
Content-Type: application/json

### update profile
PUT  http://localhost:4000/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Fname": "ss",
  "Lname":"",
  "phone":"0999999",
  "country":"",
  "shop_name":"shop",
  "shop_phone":"123"
}
### Get technical
GET http://localhost:4000/technical
Content-Type: application/json
### Get my product
GET http://localhost:4000/getMyProduct
Authorization: Bearer {{token}}
Content-Type: application/json

# product data same for all product
### Add battery
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{

  "productData": {
    "category": "battery",
    "price": "320",
    "name": "Luminous Inverlast Pro 12V 230Ah Tall Tubular Battery",
    "description": "Heavy-duty 12V 230Ah tall tubular lead-acid battery designed for deep cycle solar applications, with long service life and low maintenance."
     },
  "additionalData": {
    "batteryType": "tubular",
    "batterySize": "230"
  }
}



### Update battery
put http://localhost:4000/updateProduct/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData":{
    "category":"battery"
  },
  "additionalData":{
    "batteryType":"tubular",
    "batterySize":"100"
  }
}
###add inverter
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData": {
    "category": "inverter",
    "price": "1800",
    "name": "SUNPOLO 8.2KW Hybrid Solar Inverter",
    "description": "8.2kW hybrid solar inverter with dual MPPT, 48V battery support, pure sine wave output, and grid/off-grid capability."
    
  },
  "additionalData": {
    "inverterRatingP": "8000",
    "maxAc": "34.8",
    "defaultAc": "30",
    "solarRatingP": "8000",
    "maxSolarVolt": "450",
    "Mppt": "2"
  }
}


### Add solar panel
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData": {
    "category": "solar_panel",
    "price": "250",
    "name": "Monocrystalline Solar Panel 450W"
  },
  "additionalData": {
    "maximumPower": "450",
    "shortCurrent": "10.5",
    "openVoltage": "49.5"
  }
}


### Add other
POST http://localhost:4000/addProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productData":{
    "category":"other",
    "price":"100",
    "name": "solar panel"

  }
}

### delete product
delete http://localhost:4000/deleteProduct/16
Authorization: Bearer {{token}}
Content-Type: application/json

### Add Review
POST http://localhost:4000/addReview/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "review": "Average performance. It does the job, but I’ve seen better options in the same price range.",
  "stars": 3
}


###test add product with picture in cmd 
curl -X POST http://localhost:4000/addProduct ^
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc1NjkzNjY5OSwiZXhwIjoxNzU2OTQ3NDk5fQ.SDh8IpLTJ7Nb11BpXNxLxpMFMv05SCfp7BwIs8WgoG0" ^
  -F "productData={\"category\":\"inverter\",\"price\":\"10\",\"name\":\"inverter2\"}" ^
  -F "additionalData={\"inverterRatingP\":\"2\"}" ^
  -F "picture=@profile.jpg"

### Get all product
GET http://localhost:4000/getAllProduct
Content-Type: application/json

### Get product
GET http://localhost:4000/getProduct/1
Content-Type: application/json

### Upload profile picture
# in cmd 
curl -X POST http://localhost:4000/upload-profile-pic ^
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc1NjkzNjY5OSwiZXhwIjoxNzU2OTQ3NDk5fQ.SDh8IpLTJ7Nb11BpXNxLxpMFMv05SCfp7BwIs8WgoG0" ^
  -F "profilePic=@profile.jpg"

### Fetch chat messages just between you and user 5
GET http://localhost:4000/chat/2
Authorization: Bearer {{token}}

### Fetch chat messages
GET http://localhost:4000/chats
Authorization: Bearer {{token}}


### Estimate Solar Energy
#uvicorn solar_api:app --reload بستخدم هي التعليمة لشغل هي 
POST http://127.0.0.1:8000/estimate_energy
Content-Type: application/json

{
  "latitude": 33.5138,
  "longitude": 36.2765,
  "area": 1.6,
  "start_date": "2025-06-01",
  "end_date": "2025-06-07"
}
###solarSupplies
POST http://localhost:4000/solarSupplies
Content-Type: application/json

{
 "latitude": 33.5138,
  "longitude": 36.2765,
  "solarPanel": 450,
  "numNight": 3,
  "eDay": 3,
  "eNight": 3,
  "batteryType": "tubular"
}
###Solar Panel Orientation
POST http://localhost:4000/SolarPanelOrientation
Content-Type: application/json

{
  "latitude": 25.276987,
  "longitude": 55.296249
}
